openapi: 3.0.3
info:
  title: 恐龍故事書 API
  description: |
    恐龍故事書系統的 API 契約。
    
    此 API 提供恐龍資料的讀取功能，支援：
    - 取得所有恐龍列表
    - 根據 ID 取得單隻恐龍
    - 搜尋恐龍
    
    **注意**: 此為練習專案，資料來自 JSON 檔案，無需認證。
  version: 1.0.0
  contact:
    name: StoryBook Team

servers:
  - url: /api/v1
    description: API 基礎路徑

paths:
  /dinosaurs:
    get:
      summary: 取得所有恐龍
      description: 返回所有恐龍的列表，依 JSON 檔案定義順序排列
      operationId: getDinosaurs
      tags:
        - Dinosaurs
      parameters:
        - name: lang
          in: query
          description: 語言代碼（用於搜尋時的欄位匹配）
          required: false
          schema:
            type: string
            enum: [zh, en]
            default: zh
      responses:
        '200':
          description: 成功返回恐龍列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Dinosaur'
                  total:
                    type: integer
                    description: 恐龍總數
                    example: 8
        '500':
          $ref: '#/components/responses/InternalServerError'

  /dinosaurs/search:
    get:
      summary: 搜尋恐龍
      description: 根據關鍵字搜尋恐龍，比對名稱和介紹文字
      operationId: searchDinosaurs
      tags:
        - Dinosaurs
      parameters:
        - name: q
          in: query
          description: 搜尋關鍵字
          required: true
          schema:
            type: string
            minLength: 1
            example: 暴龍
        - name: lang
          in: query
          description: 搜尋語言
          required: false
          schema:
            type: string
            enum: [zh, en]
            default: zh
      responses:
        '200':
          description: 成功返回搜尋結果
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/DinosaurSummary'
                  total:
                    type: integer
                    description: 符合條件的恐龍數量
                  query:
                    type: string
                    description: 搜尋關鍵字
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /dinosaurs/{id}:
    get:
      summary: 取得單隻恐龍
      description: 根據 ID 取得恐龍的完整資訊
      operationId: getDinosaurById
      tags:
        - Dinosaurs
      parameters:
        - name: id
          in: path
          description: 恐龍 ID（如 tyrannosaurus）
          required: true
          schema:
            type: string
            pattern: '^[a-z0-9\-]+$'
            example: tyrannosaurus
      responses:
        '200':
          description: 成功返回恐龍資訊
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dinosaur'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /dinosaurs/index/{index}:
    get:
      summary: 根據索引取得恐龍
      description: 根據索引位置取得恐龍（用於換頁功能）
      operationId: getDinosaurByIndex
      tags:
        - Dinosaurs
      parameters:
        - name: index
          in: path
          description: 索引位置（從 0 開始）
          required: true
          schema:
            type: integer
            minimum: 0
            example: 0
      responses:
        '200':
          description: 成功返回恐龍資訊
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Dinosaur'
                  index:
                    type: integer
                    description: 當前索引
                  total:
                    type: integer
                    description: 恐龍總數
                  hasPrevious:
                    type: boolean
                    description: 是否有上一隻
                  hasNext:
                    type: boolean
                    description: 是否有下一隻
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    LocalizedText:
      type: object
      description: 多語言文字
      required:
        - zh
        - en
      properties:
        zh:
          type: string
          description: 繁體中文內容
          example: 暴龍
        en:
          type: string
          description: 英文內容
          example: Tyrannosaurus Rex

    DinosaurImages:
      type: object
      description: 恐龍圖片資訊
      required:
        - main
      properties:
        main:
          type: string
          description: 主要圖片路徑
          example: /images/dinosaurs/tyrannosaurus/main.png
        story:
          type: array
          description: 故事插圖路徑列表
          items:
            type: string
          example:
            - /images/dinosaurs/tyrannosaurus/story-1.png

    Dinosaur:
      type: object
      description: 恐龍完整資訊
      required:
        - id
        - name
        - period
        - diet
        - location
        - description
        - images
      properties:
        id:
          type: string
          description: 唯一識別碼
          pattern: '^[a-z0-9\-]+$'
          example: tyrannosaurus
        name:
          $ref: '#/components/schemas/LocalizedText'
        period:
          $ref: '#/components/schemas/LocalizedText'
        diet:
          $ref: '#/components/schemas/LocalizedText'
        location:
          $ref: '#/components/schemas/LocalizedText'
        size:
          $ref: '#/components/schemas/LocalizedText'
        description:
          $ref: '#/components/schemas/LocalizedText'
        story:
          $ref: '#/components/schemas/LocalizedText'
        images:
          $ref: '#/components/schemas/DinosaurImages'

    DinosaurSummary:
      type: object
      description: 恐龍摘要（用於搜尋結果）
      required:
        - id
        - name
        - mainImage
      properties:
        id:
          type: string
          description: 唯一識別碼
          example: tyrannosaurus
        name:
          $ref: '#/components/schemas/LocalizedText'
        mainImage:
          type: string
          description: 主要圖片路徑
          example: /images/dinosaurs/tyrannosaurus/main.png

    ProblemDetails:
      type: object
      description: RFC 7807 Problem Details 格式
      properties:
        type:
          type: string
          description: 問題類型 URI
          example: https://tools.ietf.org/html/rfc7807
        title:
          type: string
          description: 簡短說明
          example: 找不到資源
        status:
          type: integer
          description: HTTP 狀態碼
          example: 404
        detail:
          type: string
          description: 詳細說明
          example: 找不到 ID 為 'unknown' 的恐龍
        instance:
          type: string
          description: 發生問題的 URI
          example: /api/v1/dinosaurs/unknown

  responses:
    BadRequest:
      description: 請求參數錯誤
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
          example:
            type: https://tools.ietf.org/html/rfc7807
            title: 請求參數錯誤
            status: 400
            detail: 搜尋關鍵字不可為空

    NotFound:
      description: 找不到資源
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
          example:
            type: https://tools.ietf.org/html/rfc7807
            title: 找不到資源
            status: 404
            detail: 找不到指定的恐龍

    InternalServerError:
      description: 伺服器內部錯誤
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetails'
          example:
            type: https://tools.ietf.org/html/rfc7807
            title: 伺服器錯誤
            status: 500
            detail: 處理請求時發生錯誤，請稍後再試

tags:
  - name: Dinosaurs
    description: 恐龍資料相關 API
